version: "3"
services:
  ##########################
  ### SETUP SERVER CONTAINER
  ##########################
  backend:
    image: apotdevin/thunderhub-server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3001"
    volumes:
      - ./server/
    restart: always
  ##########################
  ### SETUP CLIENT CONTAINER
  ##########################
  frontend:
    image: apotdevin/thunderhub-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./client/
    depends_on:
      - backend
    restart: always
